name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Publish APK
      uses: actions/upload-artifact@v3
      with:
        name: Application-release.apk
        path: Application/build/outputs/apk/release/Application-release.apkß
        
    - name: Prepare Keystore and properties
      run: |
        echo "${{secrets.ANDROID_KEYSTORE}}" > keystore.asc
        mkdir Application/keystore
        gpg -d --passphrase "${{secrets.ANDROID_KEYSTORE_PASSPHRASE}}" --
batch android-keystore.asc > Application/keystore/keystore.jks echo "storePassword=${{secrets.ANDROID_KEYSTORE_PASSPHRASE}}" >> gradle.properties echo "keyPassword=${{secrets.ANDROID_KEYSTORE_PASSPHRASE}}" >> gradle.properties

    - name: Final Check with Jar Signer
      run: |
        jarsigner -verify -verbose -certs path/to/release.apk
